apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |-
    filebeat.inputs:
      - type: log
        paths:
          - /usr/share/filebeat/logs/**/*.log
    output.elasticsearch:
      hosts: ["elasticsearch:9200"]
    # output.logstash:
    #   hosts: ["logstash:5400"]  
