apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |-
    filebeat.inputs:
      - type: log
        paths:
          - /usr/share/filebeat/logs/default_rentsathi-deployment-*/**/*.log

    output.logstash:
      hosts: ["logstash:5400"]  
