version: '3.8'

services:
  mysql-service:
    image: mysql:8.0
    container_name: rents-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 211119
      MYSQL_DATABASE: rentsystem
      # MYSQL_USER: root
      # MYSQL_PASSWORD: 211119
    ports:
      - "3306:3306"
    networks:
      - rentnetwork

  app:
    build: .
    container_name: rent-app
    restart: always
    depends_on:
      - mysql-service
    # environment:
    #   SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3307/imsdb
    #   SPRING_DATASOURCE_USERNAME: root
    #   SPRING_DATASOURCE_PASSWORD: 211119
    ports:
      - "8081:8080"
    networks:
      - rentnetwork

networks:
  rentnetwork:
    driver: bridge