Vagrant.configure("2") do |config|
  config.vm.define "kube_master" do |vm1|
     vm1.vm.box = "centos/7"
     vm1.vm.network "private_network", ip: "192.168.56.24", name: "VirtualBox Host-Only Ethernet Adapter"
     vm1.vm.provider "virtualbox" do |vm1_prov|
     vm1.vm.hostname = "master1.devops"
       vm1_prov.gui = false
       vm1_prov.memory =  2048
       vm1_prov.cpus = 2
       vm1_prov.name = "kube_master"
     end 
   end
   config.vm.define "kube_worker" do |vm2|
     vm2.vm.box = "centos/7"
     vm2.vm.hostname = "worker.devops"
     vm2.vm.network "private_network", ip: "192.168.56.26", name: "VirtualBox Host-Only Ethernet Adapter"
     vm2.vm.provider "virtualbox" do |vm2_prov|
       vm2_prov.gui = false
       vm2_prov.memory =  8000 
       vm2_prov.cpus = 2
       vm2_prov.name = "kube_worker"  
     end
  
   end  
 
   config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/add_pub.key"
   config.vm.provision "shell", inline: <<-SHELL
     sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
     sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
     yum install -y --disableplugin=fastestmirror epel-release
     groupadd kube && useradd kube -g kube -G wheel
     echo 'kube@123' | passwd kube --stdin
     su kube -c "mkdir -p /home/kube/.ssh && touch /home/kube/.ssh/authorized_keys && chmod 600 /home/kube/.ssh/authorized_keys"
     cat /home/vagrant/add_pub.key | tee -a /home/vagrant/.ssh/authorized_keys /home/kube/.ssh/authorized_keys
     rm -f /home/vagrant/add_pub.key
     ### INSTALLING AND CONFIGURING KUBERNETES COMPONENTS
     /bin/sh /vagrant/kube_init.sh
   SHELL
 end