apiVersion: apps/v1
kind: Deployment
metadata:
  name: rentsathi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rentsathi
  template:
    metadata:
      labels:
        app: rentsathi
    spec:
      containers:
      - name: rentsathi-container
        image: bandhu8/rentsathi:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql-service:3306/rentsystem"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db-root-password
