apiVersion: v1
kind: Service
metadata:
  name: rentsathi-service
spec:
  selector:
    app: rentsathi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer  # Use LoadBalancer for external access or NodePort for local clusters
