
name: Deploy Laravel to VPS

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3


      # Step 2: Set up SSH key for connecting to the VPS
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your private SSH key in GitHub Secrets

      - name: Add EC2 host to known hosts
        run: ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: Add GitHub to known hosts
        run: ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      # Step 3: Clone the repository and set up the .env file on VPS
      - name: Clone the repository and set up .env file
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}  << 'EOF'
          # Change to the directory where you want to store the project

          # Clone the repository (this will only happen if the project doesn't already exist)
          if [ ! -d "RentSathi" ]; then
            echo "cloning"
            git clone https://github.com/samratsapkota/RentSathi.git
          else
            echo "repo exists"
            git config --global --add safe.directory /home/newuser
            cd RentSathi
            git pull origin main # Pull the latest changes if the repo already exists
            echo "git pulled"
          fi

          EOF

      
